//go:build x11

package x11

// jsCodeToX11Keycode maps JavaScript KeyboardEvent.code values to X11 keycodes.
// The mapping is based on the evdev keycodes used by the Linux kernel, which is a
// common standard for X11 keycode assignments. X11 keycodes start at 8.
var jsCodeToX11Keycode = map[string]byte{
	"Unidentified":    248, // KEY_UNKNOWN
	"Escape":          9,   // KEY_ESC
	"Digit1":          10,  // KEY_1
	"Digit2":          11,  // KEY_2
	"Digit3":          12,  // KEY_3
	"Digit4":          13,  // KEY_4
	"Digit5":          14,  // KEY_5
	"Digit6":          15,  // KEY_6
	"Digit7":          16,  // KEY_7
	"Digit8":          17,  // KEY_8
	"Digit9":          18,  // KEY_9
	"Digit0":          19,  // KEY_0
	"Minus":           20,  // KEY_MINUS
	"Equal":           21,  // KEY_EQUAL
	"Backspace":       22,  // KEY_BACKSPACE
	"Tab":             23,  // KEY_TAB
	"KeyQ":            24,  // KEY_Q
	"KeyW":            25,  // KEY_W
	"KeyE":            26,  // KEY_E
	"KeyR":            27,  // KEY_R
	"KeyT":            28,  // KEY_T
	"KeyY":            29,  // KEY_Y
	"KeyU":            30,  // KEY_U
	"KeyI":            31,  // KEY_I
	"KeyO":            32,  // KEY_O
	"KeyP":            33,  // KEY_P
	"BracketLeft":     34,  // KEY_LEFTBRACE
	"BracketRight":    35,  // KEY_RIGHTBRACE
	"Enter":           36,  // KEY_ENTER
	"ControlLeft":     37,  // KEY_LEFTCTRL
	"KeyA":            38,  // KEY_A
	"KeyS":            39,  // KEY_S
	"KeyD":            40,  // KEY_D
	"KeyF":            41,  // KEY_F
	"KeyG":            42,  // KEY_G
	"KeyH":            43,  // KEY_H
	"KeyJ":            44,  // KEY_J
	"KeyK":            45,  // KEY_K
	"KeyL":            46,  // KEY_L
	"Semicolon":       47,  // KEY_SEMICOLON
	"Quote":           48,  // KEY_APOSTROPHE
	"Backquote":       49,  // KEY_GRAVE
	"ShiftLeft":       50,  // KEY_LEFTSHIFT
	"Backslash":       51,  // KEY_BACKSLASH
	"KeyZ":            52,  // KEY_Z
	"KeyX":            53,  // KEY_X
	"KeyC":            54,  // KEY_C
	"KeyV":            55,  // KEY_V
	"KeyB":            56,  // KEY_B
	"KeyN":            57,  // KEY_N
	"KeyM":            58,  // KEY_M
	"Comma":           59,  // KEY_COMMA
	"Period":          60,  // KEY_DOT
	"Slash":           61,  // KEY_SLASH
	"ShiftRight":      62,  // KEY_RIGHTSHIFT
	"NumpadMultiply":  63,  // KEY_KPASTERISK
	"AltLeft":         64,  // KEY_LEFTALT
	"Space":           65,  // KEY_SPACE
	"CapsLock":        66,  // KEY_CAPSLOCK
	"F1":              67,  // KEY_F1
	"F2":              68,  // KEY_F2
	"F3":              69,  // KEY_F3
	"F4":              70,  // KEY_F4
	"F5":              71,  // KEY_F5
	"F6":              72,  // KEY_F6
	"F7":              73,  // KEY_F7
	"F8":              74,  // KEY_F8
	"F9":              75,  // KEY_F9
	"F10":             76,  // KEY_F10
	"NumLock":         77,  // KEY_NUMLOCK
	"ScrollLock":      78,  // KEY_SCROLLLOCK
	"Numpad7":         79,  // KEY_KP7
	"Numpad8":         80,  // KEY_KP8
	"Numpad9":         81,  // KEY_KP9
	"NumpadSubtract":  82,  // KEY_KPMINUS
	"Numpad4":         83,  // KEY_KP4
	"Numpad5":         84,  // KEY_KP5
	"Numpad6":         85,  // KEY_KP6
	"NumpadAdd":       86,  // KEY_KPPLUS
	"Numpad1":         87,  // KEY_KP1
	"Numpad2":         88,  // KEY_KP2
	"Numpad3":         89,  // KEY_KP3
	"Numpad0":         90,  // KEY_KP0
	"NumpadDecimal":   91,  // KEY_KPDOT
	"IntlBackslash":   94,  // KEY_102ND
	"F11":             95,  // KEY_F11
	"F12":             96,  // KEY_F12
	"IntlRo":          97,  // KEY_RO
	"Convert":         102, // KEY_HENKAN
	"KanaMode":        101, // KEY_KATAKANAHIRAGANA
	"NonConvert":      100, // KEY_MUHENKAN
	"NumpadEnter":     104, // KEY_KPENTER
	"ControlRight":    105, // KEY_RIGHTCTRL
	"NumpadDivide":    106, // KEY_KPSLASH
	"PrintScreen":     107, // KEY_SYSRQ
	"AltRight":        108, // KEY_RIGHTALT
	"Home":            110, // KEY_HOME
	"ArrowUp":         111, // KEY_UP
	"PageUp":          112, // KEY_PAGEUP
	"ArrowLeft":       113, // KEY_LEFT
	"ArrowRight":      114, // KEY_RIGHT
	"End":             115, // KEY_END
	"ArrowDown":       116, // KEY_DOWN
	"PageDown":        117, // KEY_PAGEDOWN
	"Insert":          118, // KEY_INSERT
	"Delete":          119, // KEY_DELETE
	"AudioVolumeMute": 121, // KEY_MUTE
	"AudioVolumeDown": 122, // KEY_VOLUMEDOWN
	"AudioVolumeUp":   123, // KEY_VOLUMEUP
	"Power":           124, // KEY_POWER
	"NumpadEqual":     125, // KEY_KPEQUAL
	"Pause":           127, // KEY_PAUSE
	"NumpadComma":     129, // KEY_KPCOMMA
	"IntlYen":         132, // KEY_YEN
	"MetaLeft":        133, // KEY_LEFTMETA
	"MetaRight":       134, // KEY_RIGHTMETA
	"ContextMenu":     135, // KEY_COMPOSE
	"Stop":            136, // KEY_STOP
	"Again":           137, // KEY_AGAIN
	"Props":           138, // KEY_PROPS
	"Undo":            139, // KEY_UNDO
	"Front":           140, // KEY_FRONT
	"Copy":            141, // KEY_COPY
	"Open":            142, // KEY_OPEN
	"Paste":           143, // KEY_PASTE
	"Find":            144, // KEY_FIND
	"Cut":             145, // KEY_CUT
	"Help":            146, // KEY_HELP
	"F13":             191, // KEY_F13
	"F14":             192, // KEY_F14
	"F15":             193, // KEY_F15
	"F16":             194, // KEY_F16
	"F17":             195, // KEY_F17
	"F18":             196, // KEY_F18
	"F19":             197, // KEY_F19
	"F20":             198, // KEY_F20
	"F21":             199, // KEY_F21
	"F22":             200, // KEY_F22
	"F23":             201, // KEY_F23
	"F24":             202, // KEY_F24
}
